Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using BaiTapWeb.Models;
namespace BaiTapWeb.Controllers
{
    public class CategoryController : Controller
    {
        PRODUCT_MANAGERContext _context = new PRODUCT_MANAGERContext();

        public IActionResult Index()
        {


            return View(_context.Categories.ToList());
        }
        public bool createCategory(string code, string name, string decription)
        {
            if (_context.Categories.Where(x => x.Code == code).ToList().Count() > 0)
            {
                return false;
            }
            Category category = new Category();
            category.Code = code;
            category.Name = name;
            category.Description = decription;

            _context.Categories.Add(category);
            _context.SaveChanges();
            return true;
        }
        public bool updateCategory(string code, string name, string decription,int id)
        {
            Category category = _context.Categories.Find(id);


            if (category == null)
            {
                return false;
            }
            category.Name = name;
            category.Description = decription;
            _context.SaveChanges();

            return true;
        }
        public bool DeleteCategory(int id)
        {
            if(id == null)
            {
                return false;
            }
            Category category = _context.Categories.Find(id);
            Category categoryDefal = _context.Categories.Where(x => x.Code.Equals("d755d326-57a7-41fb-bb9a-841ee4f23b02")).First();

            var listProduct = _context.Products.Where(x => x.CategoryId == category.Id);
            for (int i = 0; i < listProduct.ToList().Count; i++)
            {
                listProduct.ToList()[i].CategoryId = categoryDefal.Id;
            }
            _context.SaveChanges();

            _context.Categories.Remove(category);
            _context.SaveChanges();


            return true;
        }
    }
}

Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using BaiTapWeb.Models;
using Microsoft.AspNetCore.Session;
namespace BaiTapWeb.Controllers
{
    public class CustomerController : Controller
    {
        PRODUCT_MANAGERContext _context = new PRODUCT_MANAGERContext();

        public IActionResult Index()
        {


            return View(_context.Customers.ToList());
        }
        public bool createCustomer(String code,String name)
        {
            if(_context.Customers.Where(x => x.Code == code).ToList().Count() > 0)
            {
                return false;
            }
            Customer customer = new Customer();
            customer.Code = code;
            customer.Name = name;

            _context.Customers.Add(customer);
            _context.SaveChanges();
            return true;
        }
        public bool updateCustomer(String code, String name,int id)
        {
            Customer customer = _context.Customers.Find(id);
            

            if (customer == null)
            {
                return false;
            }
            customer.Name = name;
            _context.SaveChanges();
            return true;
        }

        public bool DeleteCustomer(int id)
        {
            if(id == null)
            {
                return false;
            }
            var orders =  _context.Orders.Where(x => x.CustomerId == id);
            if (orders != null)
            {
                for(int i = 0; i < orders.ToList().Count; i++)
                {
                    var item = orders.ToList()[i];
                    _context.OrderDetails.RemoveRange(_context.OrderDetails.Where(x => x.OrderId == item.Id));
                }

                _context.Orders.RemoveRange(orders);


            }
            _context.Customers.RemoveRange(_context.Customers.Where(x => x.CustomerId == id));
            _context.SaveChanges();
            return true;
        }


    }

}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using BaiTapWeb.Models;
using PagedList;
namespace BaiTapWeb.Controllers
{
    public class OrderController : Controller
    {
        PRODUCT_MANAGERContext _context = new PRODUCT_MANAGERContext();

        public IActionResult Index(int? page)
        {
            var orders = _context.VOrders.OrderBy(o => o.Date).ToList();


            var countOrder = orders.Count();

            var countPage = (countOrder % 10 == 0 ? countOrder / 10 : countOrder / 10 + 1);
            ViewBag.countPage = countPage;

            if (page == null) page = 1;
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            ViewBag.page = page;

            return View(orders.ToPagedList(pageNumber, pageSize));

        }
        public IActionResult NewsOrder(int id)
        {
            var products = _context.VProducts.ToList();

            ViewBag.idCustomer = id;

            return View(products);
        }
        public bool saveOrder(List<ItemOrder> arr, int idCustomer)
        {
            if(arr== null || idCustomer == null)
            {
                return false;
            }

            List<Product> products = new List<Product>();
            double totle = 0;
            foreach (var item in arr)
            {
                 
                totle += (item.Price * item.Quantity);
            }

            Order order = new Order();
            order.Date = DateTime.Now;
            order.Total = totle;
            order.CustomerId = idCustomer;
            _context.Orders.Add(order);

            

            _context.SaveChanges() ;
            int idOrder = order.Id;
            foreach (var item in arr)
            {
               OrderDetail orderdetail = new OrderDetail();
               orderdetail.OrderId = idOrder;
                orderdetail.ProductId = item.Id;
                orderdetail.Qty = item.Quantity;
                orderdetail.Total = item.Price * item.Quantity;
                orderdetail.Description = item.Description;
                _context.OrderDetails.Add(orderdetail);
            }
            _context.SaveChanges();


            return true;
        }

        public IActionResult DetailOrder(int id)
        {
            Order order = _context.Orders.Find(id);
            Customer customer = _context.Customers.Find(order.CustomerId);

    
         

           var products =  _context.OrderDetails.Join(_context.Products, o => o.ProductId, p => p.Id, (o, p) => new { o, p }).Where(x => x.o.OrderId == id);


            ViewBag.customer = customer;
            ViewBag.products = products;
            return View(order);
        }

        public bool DeleteOrder(int id)
        {
            if(id == null)
            {
                return false;
            }
            _context.OrderDetails.RemoveRange(_context.OrderDetails.Where(x => x.OrderId == id));
            _context.Orders.RemoveRange(_context.Orders.Where(x => x.Id == id));
            _context.SaveChanges();
            return true;
        }
    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using BaiTapWeb.Models;
using PagedList;
namespace BaiTapWeb.Controllers
{
    public class ProductController : Controller
    {
        PRODUCT_MANAGERContext _context = new PRODUCT_MANAGERContext();

        public IActionResult Index(int? page,int idCategory = -1)
        {
            var products = _context.VProducts.ToList();

            if( idCategory != -1)
            {
                products = _context.VProducts.Where(p => p.CategoryId == idCategory).ToList();
            }
        

            var countProduct = products.Count();

            var countPage = (countProduct % 10 == 0 ? countProduct / 10 : countProduct / 10 + 1);
            var categorys = _context.Categories.ToList();
            ViewBag.categorys = categorys;
            ViewBag.countPage = countPage;
            ViewBag.idCategory = idCategory;

            if (page == null) page = 1;
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            ViewBag.page = page;

            return View(products.ToPagedList(pageNumber,pageSize));
        }

        public IActionResult SearchProduct(String data)
        {
            var products = _context.VProducts.Where(p => p.Code.Contains(data)||p.Name.Contains(data)).ToList();

            return Json(products);
        }

        public IActionResult CreateProduct()
        {
            return View(_context.Categories.ToList());
        }
        public bool addProduct(string code,string name,float price,int category,string discription)
        {
            if (_context.Products.Where(x => x.Code == code).ToList().Count() > 0)
            {
                return false;
            }

            Product product = new Product();
            product.Code = code;
            product.Name = name;
            product.Price = price;
            product.Description = discription;
            product.CategoryId = category;

            _context.Products.Add(product);
            _context.SaveChanges();

            return true;
        }
        public IActionResult EditProduct(int id)
        {
            ViewBag.Categories = _context.Categories.ToList();
            return View(_context.Products.Find(id));
        }
        public bool EditProductResult(int id,string name,float price,string description,int idCategory)
        {
            Product product = _context.Products.Find(id);
            if(product == null)
            {
                return false;
            }
            product.Name = name;
            product.Price = price;
            product.Description = description;
            product.CategoryId = idCategory;
            _context.SaveChanges();
            return true;
        }

        public bool DeleteProduct(int id)
        {
            if(id== null)
            {
                return false;
            }
            _context.OrderDetails.RemoveRange(_context.OrderDetails.Where(x => x.ProductId == id));
            _context.Products.RemoveRange(_context.Products.Where(x => x.Id == id));
            _context.SaveChanges();

            return true;
        }
    }
}

Views/Shared/_Layout.cshtml
 <!DOCTYPE HTML>
<html lang="en">

<!-- Mirrored from www.ecommerce-admin.com/demo/page-products-table.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 07 Dec 2021 02:38:57 GMT -->
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>@ViewData["Title"]</title>

   
  <link href="~/images/favicon.ico" rel="shortcut icon" type="image/x-icon">

  <link href="~/css/bootstrapf9e3.css?v=1.1" rel="stylesheet" type="text/css"/>

  <!-- custom style -->
  <link href="~/css/uif9e3.css?v=1.1" rel="stylesheet" type="text/css"/>
  <link href="~/css/responsivef9e3.css?v=1.1" rel="stylesheet" />

  <!-- iconfont -->
  <link rel="stylesheet" href="~/fonts/material-icon/css/round.css"/>
  
  

</head>
<body>

<b class="screen-overlay"></b>

<aside class="navbar-aside" id="offcanvas_aside">
    <div class="aside-top">
      <a href="/Product" class="brand-wrap">
        <img src="~/images/logo.svg" height="46" class="logo" alt="Ecommerce dashboard template">
      </a>
      <div>
        <button class="btn btn-icon btn-aside-minimize"> <i class="text-muted material-icons md-menu_open"></i> </button>
      </div>
    </div> <!-- aside-top.// -->

    <nav>
      <ul class="menu-aside">
      
        <li class="menu-item">
          <a class="menu-link" asp-area="" asp-controller="Product" asp-action="Index" > <i class="icon material-icons md-shopping_bag"></i>
            <span class="text">Product</span>
          </a>
         
        </li>
        <li class="menu-item ">
          <a class="menu-link" asp-area="" asp-controller="Order" asp-action="Index"> <i class="icon material-icons md-shopping_cart"></i>
            <span class="text">Order</span>
          </a>
        
        </li>
        <li class="menu-item ">
          <a class="menu-link" asp-area="" asp-controller="Customer" asp-action="Index"> <i class="icon material-icons md-store"></i>
            <span class="text">Customer</span>
          </a>
         
        <li class="menu-item">
          <a class="menu-link"  asp-area="" asp-controller="Category" asp-action="Index"> <i class="icon material-icons md-pie_chart"></i>
            <span class="text">Category</span>
          </a>
        </li>
      </ul>
      
    </nav>
    </aside>

<main class="main-wrap">
    <header class="main-header navbar">
        <div class="col-search">
           
        </div>
        <div class="col-nav">
           <button class="btn btn-icon btn-mobile me-auto" data-trigger="#offcanvas_aside"> <i class="md-28 material-icons md-menu"></i> </button>
           <ul class="nav">
            <li class="nav-item">
                <a class="nav-link btn-icon" onclick="darkmode(this)" title="Dark mode" href="#"> <i class="material-icons md-nights_stay"></i> </a>
            </li>
            <li class="nav-item">
            </li>
            <li class="dropdown nav-item">
            
            </li>
          </ul>
        </div>
    </header>

    @RenderBody();
</main>

<script>
    if(localStorage.getItem("darkmode")){
        var body_el = document.body;
        body_el.className += 'dark';
    }
</script>

<script src="~/js/jquery-3.5.0.min.js"></script>
<script src="~/js/bootstrap.bundle.min.js"></script>
<script src="~/js/bootstrap.min.js"></script>

<!-- Custom JS -->
<script src="~/js/scriptc619.js?v=1.0"></script>
   @await RenderSectionAsync("Scripts", required: false)

</body>

<!-- Mirrored from www.ecommerce-admin.com/demo/page-products-table.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 07 Dec 2021 02:38:57 GMT -->
</html>
<script>
    var title =  document.title;
       document.querySelectorAll('.menu-item').forEach(function(item){
        //get text item
        var text = item.querySelector('.text').innerHTML;
        if(title == text){
            item.classList.add('active');
        }

    })
    function uuidv4() {
        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
          var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
          return v.toString(16);
        });
      }
</script>
   